// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MoviesColumns holds the columns for the "movies" table.
	MoviesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "genre", Type: field.TypeString, Nullable: true},
		{Name: "release_year", Type: field.TypeInt, Nullable: true},
		{Name: "poster_url", Type: field.TypeString, Nullable: true},
		{Name: "media_type", Type: field.TypeEnum, Enums: []string{"movie", "tv_series", "documentary", "anime"}, Default: "movie"},
		{Name: "watch_status", Type: field.TypeEnum, Enums: []string{"want_to_watch", "watching", "completed", "dropped"}, Default: "want_to_watch"},
		{Name: "rating", Type: field.TypeInt, Nullable: true},
		{Name: "review", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "watched_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// MoviesTable holds the schema information for the "movies" table.
	MoviesTable = &schema.Table{
		Name:       "movies",
		Columns:    MoviesColumns,
		PrimaryKey: []*schema.Column{MoviesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "movie_title",
				Unique:  false,
				Columns: []*schema.Column{MoviesColumns[1]},
			},
			{
				Name:    "movie_genre",
				Unique:  false,
				Columns: []*schema.Column{MoviesColumns[3]},
			},
			{
				Name:    "movie_watch_status",
				Unique:  false,
				Columns: []*schema.Column{MoviesColumns[7]},
			},
			{
				Name:    "movie_media_type",
				Unique:  false,
				Columns: []*schema.Column{MoviesColumns[6]},
			},
			{
				Name:    "movie_created_at",
				Unique:  false,
				Columns: []*schema.Column{MoviesColumns[11]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MoviesTable,
	}
)

func init() {
}
