// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
	"watchlist-app/ent/movie"
	"watchlist-app/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	movieFields := schema.Movie{}.Fields()
	_ = movieFields
	// movieDescTitle is the schema descriptor for title field.
	movieDescTitle := movieFields[0].Descriptor()
	// movie.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	movie.TitleValidator = movieDescTitle.Validators[0].(func(string) error)
	// movieDescRating is the schema descriptor for rating field.
	movieDescRating := movieFields[7].Descriptor()
	// movie.RatingValidator is a validator for the "rating" field. It is called by the builders before save.
	movie.RatingValidator = movieDescRating.Validators[0].(func(int) error)
	// movieDescCreatedAt is the schema descriptor for created_at field.
	movieDescCreatedAt := movieFields[10].Descriptor()
	// movie.DefaultCreatedAt holds the default value on creation for the created_at field.
	movie.DefaultCreatedAt = movieDescCreatedAt.Default.(func() time.Time)
	// movieDescUpdatedAt is the schema descriptor for updated_at field.
	movieDescUpdatedAt := movieFields[11].Descriptor()
	// movie.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	movie.DefaultUpdatedAt = movieDescUpdatedAt.Default.(func() time.Time)
	// movie.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	movie.UpdateDefaultUpdatedAt = movieDescUpdatedAt.UpdateDefault.(func() time.Time)
}
